?start: dict
        | list
        | string
        | SIGNED_NUMBER      -> number
        | "true"             -> true
        | "false"            -> false
        | "null"             -> null

list : "[" [start ("," start)*] "]"

dict : "{" [pair ("," pair)*] "}"
pair : string ":" start

string : ESCAPED_STRING

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS